[package]
edition = "2024"
name = "cohere"
version = "0.1.0"

[dependencies]
envy = "0.4.2"
once_cell = "1.21.3"
opentelemetry = "0.29.1"
opentelemetry-stdout = "0.29.0"
opentelemetry_sdk = "0.29.0"
serde = "1.0.219"
tokio = { version = "1.45.0", features = ["full"] }
